name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal packages

  ## Shared
  core:
    path: ../../shared/core
  session:
    path: ../../shared/session

  ## Infrastructure
  network:
    path: ../../infrastructure/network
  event_bus:
    path: ../../infrastructure/event_bus

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.5
  flutter_lints: ^5.0.0
  build_runner: any
  injectable_generator: ^2.8.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1