name: theming
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Internal dependencies

  ## Shared
  core:
    path: ../core
  design_system:
    path: ../design_system

  ##
  storage:
    path: ../../infrastructure/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

    # Code Generation
  build_runner: any
  injectable_generator: any