name: root
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Internal dependencies

  ## Features
  auth:
    path: ../../packages/features/auth
  app_shell:
    path: ../../packages/features/app_shell
  home:
    path: ../../packages/features/home
  profile:
    path: ../../packages/features/profile

  ## Infrastructure
  storage:
    path: ../../packages/infrastructure/storage
  event_bus:
    path: ../../packages/infrastructure/event_bus
  network:
    path: ../../packages/infrastructure/network

  ## Shared
  core:
    path: ../../packages/shared/core
  session:
    path: ../../packages/shared/session
  design_system:
    path: ../../packages/shared/design_system
  theming:
    path: ../../packages/shared/theming
  analytics:
    path: ../../packages/shared/analytics

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.4
  flutter_lints: ^5.0.0
  build_runner: any
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
