name: auth
description: "Authentication feature module with Clean Architecture and BLoC pattern."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Internal packages

  ## Shared
  core:
    path: ../../shared/core
  config:
    path: ../../shared/config
  session:
    path: ../../shared/session
  design_system:
    path: ../../shared/design_system

  ## Infrastructure
  storage:
    path: ../../infrastructure/storage
  network:
    path: ../../infrastructure/network
  event_bus:
    path: ../../infrastructure/event_bus

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: any
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^2.8.1
  auto_route_generator: ^10.2.5

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  
