name: storage
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^5.0.0
  objectbox_generator: any