name: analytics
description: Shared analytics micro-package for event logging.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  ## Shared
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: any

  # DI Generator
  injectable_generator: any