name: profile
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Internal packages

  ## Shared
  core:
    path: ../../shared/core
  design_system:
    path: ../../shared/design_system
  theming:
    path: ../../shared/theming

  ## Infrastructure
  event_bus:
    path: ../../infrastructure/event_bus

dev_dependencies:
  auto_route_generator: ^10.2.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  injectable_generator: any
  freezed: any
  json_serializable: any